name: widgets
description: "GitMosaic - Beautiful GitHub contribution graph widgets for your home screen."
publish_to: 'none'
version: 0.1.1+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  home_widget: ^0.9.4
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
